### ISSUE TITLE
Error during message processing: Invalid signal identifier: main.msg_tree_path_elements[0][4]

### ISSUE THREAD

**Issue by xuhcc** [appliedzkp/maci#148]
I'm trying to process messages with MACI CLI (commit 19aebeb3aeca72ee9c7da01a4a600d15537c7b34). The command is:
```shell
node build/index.js process --eth-provider <url> --contract <addr> --privkey <pk> --eth-privkey <pk> --repeat
```
Output:

```
(node:22641) UnhandledPromiseRejectionWarning: Error: Invalid signal identifier: main.msg_tree_path_elements[0][4]
    at Circuit.getSignalIdx (./maci/circuits/node_modules/snarkjs/src/circuit.js:131:15)
    at RTCtx.setSignalFullName (./maci/circuits/node_modules/snarkjs/src/calculateWitness.js:154:34)
    at RTCtx.setSignal (./maci/circuits/node_modules/snarkjs/src/calculateWitness.js:104:14)
    at ./maci/circuits/node_modules/snarkjs/src/calculateWitness.js:50:17
    at iterateSelector (./maci/circuits/node_modules/snarkjs/src/calculateWitness.js:31:20)
    at iterateSelector (./maci/circuits/node_modules/snarkjs/src/calculateWitness.js:35:13)
    at iterateSelector (./maci/circuits/node_modules/snarkjs/src/calculateWitness.js:35:13)
    at calculateWitness (./maci/circuits/node_modules/snarkjs/src/calculateWitness.js:48:9)
    at Circuit.calculateWitness (./maci/circuits/node_modules/snarkjs/src/circuit.js:59:16)
    at ./maci/cli/build/process.js:190:35
(node:22641) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:22641) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Exception thrown at this line https://github.com/appliedzkp/maci/blob/master/cli/ts/process.ts#L234

**Comment by xuhcc** [comment]
MACI state:
- message tree depth: 10
- message batch size: 4
- number of messages: 2

**Comment by xuhcc** [comment]
It turned out that MACI currently can only work with these parameters:
- state tree depth = 4
- message tree depth = 4
- vote option tree depth >= 2
- tally batch size = 4
- message batch size = 4

https://github.com/appliedzkp/maci/blob/v0.1.5/cli/ts/create.ts#L250

**Comment by xuhcc** [comment]
MACI 0.2.6 now also supports `state tree depth = 8, message tree depth = 11, vote option tree depth = 3`.

So I'm closing this issue.
