### ISSUE TITLE
TypeError: poseidonGenContract.generateABI is not a function

### ISSUE THREAD

**Issue by xuhcc** [appliedzkp/maci#229]
I'm trying to compile contracts by running `npm run compileSol`, but getting this error:
```
Compiler run successful. Artifact(s) can be found in directory ./compiled.
(node:59697) UnhandledPromiseRejectionWarning: TypeError: poseidonGenContract.generateABI is not a function
    at ./maci/contracts/build/buildPoseidon.js:47:46
    at step (./maci/contracts/build/buildPoseidon.js:33:23)
    at Object.next (./maci/contracts/build/buildPoseidon.js:14:53)
    at ./maci/contracts/build/buildPoseidon.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (./maci/contracts/build/buildPoseidon.js:4:12)
    at buildPoseidonT3 (./maci/contracts/build/buildPoseidon.js:42:44)
    at Object.<anonymous> (./maci/contracts/build/buildPoseidon.js:73:5)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
```

**Comment by weijiekoh** [comment]
The `circomlib` dependency has been updated. Try running `npm run bootstrap && npm run build` again.

**Comment by xuhcc** [comment]
Yes, I did that before compiling. Will try to remove node_modules and reinstall everything from scratch.

**Comment by xuhcc** [comment]
Okay, that worked :D
