### ISSUE TITLE
In docker container, failed to run `npm run compileSol`

### ISSUE THREAD

**Issue by chnejohnson** [appliedzkp/maci#339]
```sh
root@94c75e662e0d:/maci/contracts# npm run compileSol

> maci-contracts@0.9.4 compileSol
> ./scripts/compileSol.sh

Downloading solc...
./scripts/compileSol.sh: line 25: wget: command not found
chmod: cannot access '/maci/contracts/solc': No such file or directory
Building contracts
./scripts/compileSol.sh: line 34: /maci/contracts/solc: No such file or directory
./scripts/compileSol.sh: line 35: /maci/contracts/solc: No such file or directory
node:fs:492
  handleErrorFromBinding(ctx);
  ^

Error: ENOENT: no such file or directory, open 'compiled/PoseidonT3.json'
    at Object.openSync (node:fs:492:3)
    at Object.writeFileSync (node:fs:1516:35)
    at writeArtifact (/maci/contracts/node_modules/truffle-artifactor/utils.js:6:7)
    at Artifactor.save (/maci/contracts/node_modules/truffle-artifactor/index.js:35:16)
    at /maci/contracts/build/buildPoseidon.js:46:53
    at step (/maci/contracts/build/buildPoseidon.js:33:23)
    at Object.next (/maci/contracts/build/buildPoseidon.js:14:53)
    at /maci/contracts/build/buildPoseidon.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/maci/contracts/build/buildPoseidon.js:4:12) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: 'compiled/PoseidonT3.json'
}
npm ERR! code 1
npm ERR! path /maci/contracts
npm ERR! command failed
npm ERR! command sh -c ./scripts/compileSol.sh

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-01-06T07_21_04_901Z-debug.log
```

**Comment by chnejohnson** [comment]
`sudo apt-get install wget` can fix this. Suggest to add in the DockerFile.

**Comment by barryWhiteHat** [comment]
@chnejohnson can you make PR for this ?

**Comment by chnejohnson** [comment]
Sure.
