### ISSUE TITLE
Failed to generate proofs on branch v1

### ISSUE THREAD

**Issue by chnejohnson** [appliedzkp/maci#371]
Run `maci/cli/test.sh`

Error:

```
...
fromBlock = 0
Generating proofs of message processing...
(node:2707) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'copy' of undefined
    at Poll.processMessages (/root/maci/core/ts/MaciState.ts:358:58)
    at /root/maci/cli/ts/genProofs.ts:335:36
    at step (/root/maci/cli/build/genProofs.js:33:23)
    at Object.next (/root/maci/cli/build/genProofs.js:14:53)
    at fulfilled (/root/maci/cli/build/genProofs.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:2707) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:2707) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

The problem is in maci/core/ts/MaciState.ts - `r.newStateLeaf is undefined`

https://github.com/appliedzkp/maci/blob/ff71e8cdc364728a3d2668322937a268a19811ec/core/ts/MaciState.ts#L354

**Comment by daodesigner** [comment]
https://github.com/appliedzkp/maci/pull/372

**Comment by chnejohnson** [comment]
@daodesigner still fail after #372 merged.

**Comment by daodesigner** [comment]
On it

**Comment by daodesigner** [comment]
https://github.com/appliedzkp/maci/pull/375

**Comment by chnejohnson** [comment]
@daodesigner Thanks, it works for me!

**Comment by chnejohnson** [comment]
@daodesigner I think we should wait for the merge then we can close this issue? 🤔

**Comment by daodesigner** [comment]
Is your issue resolved? That PR is unrelated to the issue you raised. Please use the fix branch until a release is cut on npm for the packages.
