### ISSUE TITLE
Tests failure of `core` subpackage of `v1`

### ISSUE THREAD

**Issue by gurrpi** [appliedzkp/maci#392]
### Symptom

```
 PASS  ts/__tests__/ProcessMessage.test.ts
  Message processing
    Process a batch of messages
      ✓ TODO: processMessage() should process a valid message
      ✓ TODO: processMessage() should not process a message with an incorrect nonce
      ✓ TODO: processMessage() should not process a message with an incorrect vote weight
      ✓ TODO: processMessage() should not process a message with an incorrect state tree index
      ✓ TODO: processMessage() should not process a message with an incorrect signature
      ✓ TODO: processMessage() should not process a message with an invalid maxVoteOptionIndex

 FAIL  ts/__tests__/MaciState.test.ts (14.177 s)
  MaciState
    Process and tally 1 message from 1 user
      ✓ the state root should be correct (33 ms)
      ✓ the message root should be correct (174 ms)
      ✓ packProcessMessageSmallVals and unpackProcessMessageSmallVals (1 ms)
      ✕ Process a batch of messages (though only 1 message is in the batch) (435 ms)
      ✓ Tally ballots (610 ms)
    Process and tally 50 messages from 25 users
      ✕ should process votes correctly (6124 ms)
      ✕ should tally ballots correctly (606 ms)
    Deep copy
      ✓ should correctly deep-copy a MaciState object (2309 ms)

  ● MaciState › Process and tally 1 message from 1 user › Process a batch of messages (though only 1 message is in the batch)

    TypeError: Cannot read properties of undefined (reading 'copy')

      352 |                 currentBallotsPathElements.unshift(r.originalBallotPathElements)
      353 |
    > 354 |                 this.stateLeaves[index] = r.newStateLeaf.copy()
          |                                                          ^
      355 |                 this.stateTree.update(index, r.newStateLeaf.hash())
      356 |
      357 |                 this.ballots[index] = r.newBallot

      at Poll.processMessages (ts/MaciState.ts:354:58)
      at Object.<anonymous> (ts/__tests__/MaciState.test.ts:181:37)

  ● MaciState › Process and tally 50 messages from 25 users › should process votes correctly

    TypeError: Cannot read properties of undefined (reading 'copy')

      352 |                 currentBallotsPathElements.unshift(r.originalBallotPathElements)
      353 |
    > 354 |                 this.stateLeaves[index] = r.newStateLeaf.copy()
          |                                                          ^
      355 |                 this.stateTree.update(index, r.newStateLeaf.hash())
      356 |
      357 |                 this.ballots[index] = r.newBallot

      at Poll.processMessages (ts/MaciState.ts:354:58)
      at Object.<anonymous> (ts/__tests__/MaciState.test.ts:317:37)

  ● MaciState › Process and tally 50 messages from 25 users › should tally ballots correctly

    expect(received).toEqual(expected) // deep equality

    Expected: "9"
    Received: "0"

      385 |             for (let i = 0; i < maciState.polls[pollId].results.length - 1; i ++) {
      386 |                 expect(maciState.polls[pollId].results[i].toString())
    > 387 |                     .toEqual(voteWeight.toString())
          |                      ^
      388 |             }
      389 |
      390 |             expect(maciState.polls[pollId].hasUntalliedBallots()).toBeFalsy()

      at Object.<anonymous> (ts/__tests__/MaciState.test.ts:387:22)

Test Suites: 1 failed, 1 passed, 2 total
Tests:       3 failed, 11 passed, 14 total
Snapshots:   0 total
Time:        14.302 s
Ran all test suites.
```

### Reproduction Procedure

```
git clone https://github.com/appliedzkp/maci
cd maci
git checkout v1

cd core
npm install
npm run test
```

#### Environment

commit: https://github.com/appliedzkp/maci/commit/b568e029895b8605e5189cd9424b23b545408e48
OS: OS X 12.2.1 (M1)
Node: v16.14.2

**Comment by gurrpi** [comment]
Fixed in https://github.com/appliedzkp/maci/pull/375
