### ISSUE TITLE
`testKeyChange.sh` Failed

### ISSUE THREAD

**Issue by gurrpi** [appliedzkp/maci#400]
## Symptom

Other tests under `/cli` passed but `testKeyChange.sh` failed.

```
VkRegistry: 0x8CdaF0CD259887258Bc13a92C0a6dA92698644C0
Setting verifying keys...
Transaction hash: 0x8273c20c91cc7aa0d4228546d1678b23b75eba95135fbe28ab5c77883d4f8a80
Deploying InitialVoiceCreditProxy
Deploying Poseidon contracts
Linking Poseidon libraries to MACI
Linking Poseidon libraries to PollFactory
Linking Poseidon libraries to MessageAqFactory
Deploying MACI
Transferring PollFactory ownership to MACI
Transferring MessageAqFactory ownership to PollFactory
Initialising MACI
MACI: 0xf204a4Ef082f5c04bB89F7D5E6568B796096735a
Verifier: 0x0d8cc4b8d15D4c3eF1d70af0071376fb26B5669b
Poll ID: 0
Poll contract: 0x08e8f54262de52fe7Dfd0Bc0C9Ea87689d70e985
PollProcessorAndTallyer contract: 0xEcFcaB0A285d3380E488A39B4BB21e777f8A4EaC
Transaction hash: 0x504cd89b637cd1993b0019641200226796acd7e720c9e99ff05c01b66969f027
State index: 1
Transaction hash: 0x23c90a2f6955f96b96aadc062df7e4fcc8d8121f7570bf87cbb76b2b8a489f1b
Ephemeral private key: macisk.1cc02d04b58795e8d4aa511bef9ad68a61de8b717d1019a9abfdccebaa43e236
Transaction hash: 0x4fc1bb6d0240ff90c426847f5003301f4a7ea204305794e6e8402eff23dbac48
Ephemeral private key: macisk.8aca63e20dd9d4f35433cc34f5bd31208156c00b982a6a20c18c4906555af32
Transaction hash: 0x1335b671577f4280346ee138e038569edb7202bcf65a94d4185edf5a6e9d8543
Ephemeral private key: macisk.2783012e8d7bdbe51680cd1e2aee794e50d9f238f3d5354cf2d2cc519bf1ace4
Merging message subroots 1 / 1
Executed mergeMaciStateAqSubRoots(); gas used: 602465
Transaction hash: 0xae660190d7ee1d828861502651c9e36022846696e822b4b111b850a4bfae1b5a

All message subtrees have been merged.
Merging subroots to a main message root...
Executed mergeMessageAq(); gas used: 174376
Transaction hash: 0xcedf95440203341b9c172d282d81c248529a9a5c82e71ee8c3e988a795ece561
The message tree has been merged.
Merging state subroots 1 / 1
Executed mergeMaciStateAqSubRoots(); gas used: 723525
Transaction hash: 0x1c0b69e0d4f61edb8b7a3b56c8e34af6708413d4b14f570ae71a94a5eb9d8ecf

All state subtrees have been merged.
Merging subroots to a main state root...
Executed mergeStateAq(); gas used: 1015876
Transaction hash: 0xb5ac5d7e2a4c203235c23b0cd1d5ebc2ae5d7414b68f63b78e6d7123b1bc750d
The state tree has been merged.
fromBlock = 0

/home/ubuntu/maci/contracts/build/genMaciState.js:44
            op = body.call(thisArg, _);
                      ^
AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:

  assert(coordinatorPubKeyOnChain[0].toString() === coordinatorKeypair.pubKey.rawPubKey[0].toString())

    at /home/ubuntu/maci/contracts/ts/genMaciState.ts:207:5
    at step (/home/ubuntu/maci/contracts/build/genMaciState.js:44:23)
    at Object.next (/home/ubuntu/maci/contracts/build/genMaciState.js:25:53)
    at fulfilled (/home/ubuntu/maci/contracts/build/genMaciState.js:16:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Error: undefined does not have the correct number of message processing proofs (expected 1, got 0.
Submitting proofs of message processing...

/home/ubuntu/maci/cli/build/proveOnChain.js:33
            op = body.call(thisArg, _);
                      ^
TypeError: Cannot read properties of undefined (reading 'proof')
    at /home/ubuntu/maci/cli/ts/proveOnChain.ts:252:22
    at step (/home/ubuntu/maci/cli/build/proveOnChain.js:33:23)
    at Object.next (/home/ubuntu/maci/cli/build/proveOnChain.js:14:53)
    at fulfilled (/home/ubuntu/maci/cli/build/proveOnChain.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
0
Error: unable to open  tally.json
ubuntu@ip-172-31-33-79:~/maci/cli$ ./testKeyChange.sh
VkRegistry: 0x8CdaF0CD259887258Bc13a92C0a6dA92698644C0
Setting verifying keys...
Transaction hash: 0x8273c20c91cc7aa0d4228546d1678b23b75eba95135fbe28ab5c77883d4f8a80
Deploying InitialVoiceCreditProxy
Deploying Poseidon contracts
Linking Poseidon libraries to MACI
Linking Poseidon libraries to PollFactory
Linking Poseidon libraries to MessageAqFactory
Deploying MACI
Transferring PollFactory ownership to MACI
Transferring MessageAqFactory ownership to PollFactory
Initialising MACI
MACI: 0xf204a4Ef082f5c04bB89F7D5E6568B796096735a
Verifier: 0x0d8cc4b8d15D4c3eF1d70af0071376fb26B5669b
Poll ID: 0
Poll contract: 0x08e8f54262de52fe7Dfd0Bc0C9Ea87689d70e985
PollProcessorAndTallyer contract: 0xEcFcaB0A285d3380E488A39B4BB21e777f8A4EaC
Transaction hash: 0x504cd89b637cd1993b0019641200226796acd7e720c9e99ff05c01b66969f027
State index: 1
Transaction hash: 0x141c3b1feda37b739760e8e6c4f7ed0a9ff5aea2aee0f1595acae75b72824ece
Ephemeral private key: macisk.2197f9b6cdd2f060a39fc421a5c0bc524b78aeb6d23066714d609be3aac20559
Transaction hash: 0xe5fd20b85202e516e68c92ffb9f8dcb47ce0f5c5d08f6db7172b656475a9855e
Ephemeral private key: macisk.1b1c775c79177bcca0aeaf5368686a6bcfa26f5f7b27187f3304a359c1a4a0e8
Transaction hash: 0x2aefa61e47c6983eec88f92f77b3307f403b568ab50c4c4b1e9f9d3d25b67df7
Ephemeral private key: macisk.297b320079aa9201a39029fe92a9c86e474816a0618b422c729e8ddea51c800
Merging message subroots 1 / 1
Executed mergeMaciStateAqSubRoots(); gas used: 602465
Transaction hash: 0x21b07b318bb5dd3d2edf53a9d92beb39991f5c06920765ab3587cf3b970f0da4

All message subtrees have been merged.
Merging subroots to a main message root...
Executed mergeMessageAq(); gas used: 174376
Transaction hash: 0x464af7bd3495e10fce394545fec0e4c821fc444b816db319779aa984cd3ee5d6
The message tree has been merged.
Merging state subroots 1 / 1
Executed mergeMaciStateAqSubRoots(); gas used: 723525
Transaction hash: 0xa82da1a9089a1fe4d2adcdb5572e5078ce8b52464c045bbdb27fb5b0a145d3a5

All state subtrees have been merged.
Merging subroots to a main state root...
Executed mergeStateAq(); gas used: 1015876
Transaction hash: 0xde502154fbf31b1fb283922a781f311e6e3ad2106a74aa46242119e236e95e11
The state tree has been merged.
fromBlock = 0

/home/ubuntu/maci/contracts/build/genMaciState.js:44
            op = body.call(thisArg, _);
                      ^
AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:

  assert(coordinatorPubKeyOnChain[0].toString() === coordinatorKeypair.pubKey.rawPubKey[0].toString())

    at /home/ubuntu/maci/contracts/ts/genMaciState.ts:207:5
    at step (/home/ubuntu/maci/contracts/build/genMaciState.js:44:23)
    at Object.next (/home/ubuntu/maci/contracts/build/genMaciState.js:25:53)
    at fulfilled (/home/ubuntu/maci/contracts/build/genMaciState.js:16:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Error: undefined does not have the correct number of message processing proofs (expected 1, got 0.
Submitting proofs of message processing...

/home/ubuntu/maci/cli/build/proveOnChain.js:33
            op = body.call(thisArg, _);
                      ^
TypeError: Cannot read properties of undefined (reading 'proof')
    at /home/ubuntu/maci/cli/ts/proveOnChain.ts:252:22
    at step (/home/ubuntu/maci/cli/build/proveOnChain.js:33:23)
    at Object.next (/home/ubuntu/maci/cli/build/proveOnChain.js:14:53)
    at fulfilled (/home/ubuntu/maci/cli/build/proveOnChain.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
0
Error: unable to open  tally.json
```

**Comment by gurrpi** [comment]
Figured out this bug has been caused by the flaw of test script. Will submit a fixed scripts soon.
